services:
  nanobot:
    image: ${DOCKER_MIRROR}docker.io/kangkang223/nanobot-webui:latest
    container_name: nanobot
    ports:
      - "${TRIM_SERVICE_PORT}:18780"
      - "18790:18790"
    volumes:
      - ${TRIM_PKGVAR}/data:/root/.nanobot
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped
